import Head from 'next/head';
import { ReactNode } from 'react';
import Footer from 'src/components/footer';
import Navbar from 'src/components/navbar';

type Props = {
  children?: ReactNode;
};

const BaseLayout: React.FC<Props> = ({ children }) => {
  return (
    <div className="h-screen flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex-1">{children}</main>
      <Footer />
    </div>
  );
};

export default BaseLayout;
