import Head from 'next/head';
import { ReactNode } from 'react';
import Navbar from 'src/components/navbar';

type Props = {
  children?: ReactNode;
};

const BaseLayout: React.FC<Props> = ({ children }) => {
  return (
    <>
      <div className="h-screen flex flex-col w-11/12 sm:w-8/10 md:w-4/7 lg:w-2/3 mx-auto">
        <Head>
          <title>Alex Lin</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <main className="flex-1">
          {children}
        </main>
      </div>
    </>
  );
};

export default BaseLayout;
